# -*- coding: utf-8 -*-
"""Copy of Forex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZVa6fSVa5iWOHXZV_qxlzgl7oaiQXYj8
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

data = pd.read_csv("Forex.txt", delimiter = "|")
data.head()

data.describe()

# importing pandas module 
import pandas as pd 

# importing regex module 
import re 

# removing null values to avoid errors 
data.dropna(inplace = True) 

# percentile list 
perc =[.20, .40, .60, .80] 

# list of dtypes to include 
include =['object', 'int'] 

# calling describe method 
desc = data.describe(percentiles = perc, include = include) 

# display 
#desc 
import matplotlib as mpl
import matplotlib.pyplot as plt

#mengubah e menjadi nilai
pd.set_option('display.float_format', lambda x: '%.5f' % x)
#data.head(15)

#CCY BUY
aku_BUY = data.groupby(["CCY"])[["BUY"]].sum()
aku_BUY.loc["Total"] = aku_BUY.sum()

#CCY BUY VALBUY
aku_ValBuy = data.groupby(["CCY"])[["Valas_BUY"]].sum()
aku_ValBuy.loc["Total"] = aku_ValBuy.sum()


#CCY BUY VALBUY IDRBUY
aku_IDRBuy = data.groupby(["CCY"])[["Valas_SALE"]].sum()
aku_IDRBuy.loc["Total"] = aku_IDRBuy.sum()
###############################################################

#CCY SALE
aku_SALE = data.groupby(["CCY"])[["SALE"]].sum()
aku_SALE.loc["Total"] = aku_SALE.sum()

#CCY SALE VALSALE
aku_ValSale = data.groupby(["CCY"])[["Valas_SALE"]].sum()
aku_ValSale.loc["Total"] = aku_ValSale.sum()

#CCY SALE IDRSALE
aku_IDRSale = data.groupby(["CCY"])[["Idr_SALE"]].sum()
aku_IDRSale.loc["Total"] = aku_IDRSale.sum()


aku_BUY['Valas BUY'] = aku_ValBuy
aku_BUY['IDR Buy'] = aku_IDRBuy
aku_BUY['SALE'] = aku_SALE
aku_BUY['Valas SALE'] = aku_ValSale
aku_BUY['IDR SALE'] = aku_IDRSale

#menghapus LIBUR
data_droplib = aku_BUY.drop('LIBUR')
data_droptot = data_droplib.drop('Total')
data_sum = data_droptot.reset_index()
data_sum

data_sum.plot(kind='bar',x='CCY',y='BUY')
data_sum.plot(kind='bar',x='CCY',y='Valas BUY')
data_sum.plot(kind='bar',x='CCY',y='IDR Buy')
data_sum.plot(kind='bar',x='CCY',y='SALE')
data_sum.plot(kind='bar',x='CCY',y='Valas SALE')
data_sum.plot(kind='bar',x='CCY',y='IDR SALE')

dfplot = data_sum[['CCY','BUY', 'SALE']].copy()
fig = plt.figure()

ax = fig.add_subplot(111)

width = 1
dfplot.plot(kind='bar', x='CCY', ax=ax, width=width, position=1)


dfplot = data_sum[['CCY','Valas BUY', 'IDR Buy']].copy()
fig = plt.figure()

ax = fig.add_subplot(111)

width = 0.8
dfplot.plot(kind='bar', x='CCY', ax=ax, width=width, position=1)

dfplot = data_sum[['CCY','Valas BUY', 'IDR Buy']].copy()
fig = plt.figure()

ax = fig.add_subplot(111)

width = 0.8
dfplot.plot(kind='bar', x='CCY', ax=ax, width=width, position=1)

dfplot = data_sum[['CCY','Valas SALE', 'IDR SALE']].copy()
fig = plt.figure()

ax = fig.add_subplot(111)

width = 0.8
dfplot.plot(kind='bar', x='CCY', ax=ax, width=width, position=1)

plt.show()

data5= data_droplib.style.format("{:,.2f}")
data5

from matplotlib.pyplot import pie, axis, show
sums = data_sum.BUY.groupby(data_sum.CCY).sum()
axis('equal');


plt.pie(sums,labels=sums.index,labeldistance=2.3,autopct='%1.1f%%',startangle=25);

show()

from matplotlib.pyplot import pie, axis, show
sums = data_sum.BUY.groupby(data_sum.CCY).sum()
axis('equal');

# only "explode" the 2nd slice (i.e. 'Hogs')
explode = (0, 0.1, 0, 0)  
fig1, ax1 = plt.subplots()
ax1.pie(sums, labels=sums.index, autopct='%1.1f%%',
        shadow=True, startangle=90)

# Equal aspect ratio ensures that pie is drawn as a circle
ax1.axis('equal')  
plt.tight_layout()
plt.show()

#plt.pie(sums,labels=sums.index,labeldistance=2.3,autopct='%1.1f%%',startangle=25);